{% set version = '1.7.14' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tmb
  version: {{ version|replace("-", "_") }}

source:
  fn: TMB_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/TMB_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/TMB/TMB_{{ version }}.tar.gz
  sha256: b499644b4bbc89f191101639ff8d9d9ec90b896ca24ca650e6aea36f0928ec2e

build:
  merge_build_host: True  # [win]
  number: 1002
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
    - llvm-openmp                # [osx]
  host:
    - r-base
    - r-matrix >=1.0_12
    - r-rcppeigen
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-matrix >=1.0_12
    - r-rcppeigen
    - llvm-openmp                # [osx]

test:
  commands:
    - $R -e "library('TMB')"           # [not win]
    - "\"%R%\" -e \"library('TMB')\""  # [win]

about:
  home: http://tmb-project.org
  license: GPL-2
  summary: 'With this tool, a user should be able to quickly implement complex random effect
    models through simple C++ templates. The package combines ''CppAD'' (C++ automatic
    differentiation), ''Eigen'' (templated matrix-vector library) and ''CHOLMOD'' (sparse
    matrix routines available from R) to obtain an efficient implementation of the applied
    Laplace approximation with exact derivatives. Key features are: Automatic sparseness
    detection, parallelism through ''BLAS'' and parallel user templates.'
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
