travis:
  secure:
    BINSTAR_TOKEN: xJQY2ajXKE45pgOgv1Zr1Jenle8vFW237sZ5eZK0zNzTwFn0xAzRbkZ2Qle/z1clrNdo6+V8GeDVwLHexyPvNNOnHucG1xVW1PLk4VQ6vI1ry9XWuwAUeAaADRY5x4gGbEX7xcqLQwTgq7AzAGMhYExZgap0Gqb4k06lP5zEY+IlK9d1kXPOWrwVp1D2WFo+yW5Nywnk4FvBwgBHhcsCoFXgB8Ea5OzlVIm+O5RSPNRnUs1/sijMVXrVrz2Dloot8AsQrynx7anQ+rUc2BTfPWFrWAjbv8tDef+m3DK5Sh9ypdLIbi1eaDI+nq8out5rxUO+upxn/1qvspeyq+/Kv6SHZl21uk9nzPEC1rIKbJc0fG5fgkwTq4OEYsXOhVFsUoggiESQzEPF6I5362OADB7oNaDTJtF8ap3ixBtstuR6iHLlL1oOScia/AdENcHeZIsKJJXtXynp7WBFazDgg6a/a4jF7lV7F+8/FHuGj9LW/l6WpUPJcSLpmLM4m4pAnTj/ztK/C5OPLNJqr/6j8PWlKetCOX+We1cJYP22LvzcvLAoJBt8VUVC570A79xsbroXWj66wVY/8O7Vp3QqvajocHbAka5mmmtimoHCiyGSDaIy8K3ONRq3bVjfP2LahxunxfIWtQAY32Ok12E9hbAV4XKAwqPqcEynLZbKlNw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
