travis:
  secure:
    BINSTAR_TOKEN: Mn0xyQXwUNmRaodqeZXbxf5w69ThfUhQM/ePYgXkDg1KIWFgMM/CS1GY/fNs8l8RYlZyGgG+JoWY9UMSoDU3Fli3ZAhr2a9UovecvZ2JOFO0w3xadCWJxIn7uYUUhe+DULafhRJl/OBMyQ5GBO3GxieK+klL5frgNSl4DfAEcXH3JzGzm7zUrtHJeHnnlLDLMFSBmwmXMbnuekmf7xBH6+WU7eFyHv3Ajr2XaHi31HCrUkWtS09KxSfbsw2XOJweh7AgeZ85WtAz5YmQb/a6N5CLI01jS8VgOgbsWxYHdDHCPxAjBa+wL7lMOggLoEAcjVugi41QANHJ1I8T2go7X24eFmtI9bSEJmnIcU1ZQdOoDliMt7mNnGSEKEjgzHD/kXnes/pMoTyj8YtSRRxY8uqoCOocPkcYiowyhMcYSIPjvthAC8XOfnYU5gmRbopdyxA0RbYSZsFEF9UfUt/p4A6jb9ByUCMGvAsXvL3R6RKGsw7Q92h5Txg7T4/zmCFpYkQtQGqRz7koNjaxMuiuCLGzDODvNQxJYV8AjMlgwhOyXytz3nSL7h+jxko0/AczkAbTFZXOX/yoij9muyGJs93oCPuO4u++XVSI7ZPuLTefnGguwCddtsUEZijQqm5l17IlmuodrIZPQnt/7uoRYrGEckSUuXjxDmDMVYzy/i0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
