appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: mwugUhTw7PD3paYKlXs6F1gaMDOLQ3LxIXl/fIqOHkaumI5pi0QsEyLK0/7zEBhLzuoF1qThafoiXRTx7Nkr4ErVVltF9mLJndzICyHzVQ6V1EdTXuiAwn5ILVAZbxSTCTIVdOKF27dO/S2LzuD6IxWi4AdMDb9WdPidxq8ZLDGcXb5kDnDGrtgybXltky25m4tnXojchH3hdnxfRrG5CAy4QX4D0rDVF4T19JptACSDFi0KbeOQcfcTxvdtBlnuqjq2JCGD5N8VBhSRpXCt01FwuDMGDrgyqGnb/vypTO6R03Hbw5hnUnximvPvr2RHLmWYNWQAN5e5o58EmDw6O3QJqhNf0hUECPeqx8oMkfO5l5orx24g6+WZ6Q8o1EDyFXg/25pNDhv4ETbKNqJzdnkrcQ0pT0kiThyrj6IWOe8ZZTM2Pg/VGyYdfgSxkNgqWfd396+Veti7vqVE0cF7AVOBMQINJz/7BchLt0YNNmcjwAHWCp2c420mVLI14mUxYizVG7+vCykLF4A85t853+SR0/6n1Daw9VvInU3W2urgP+SVKtloZHPrfqocKaEoJR/NG2fZOuIAFjHWeJB7ueAVaXOvqoHJFyTKz2Fb3B6QapIUPy3aVormXk2vhgwuROXhDl8yWWrJ6vwCrfs/naRnHtRGnbKMWtzrWMm1bYc=}
